### ISSUE TITLE
SPFarm fails test method when HTTP used for central admin

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/SharePointDsc#1065]
#### Details of the scenario you tried and the problem that is occurring

Looking over the recent changes to the SPFarm resource, I can see @ronx added some stuff around managing if central admin runs to the resource (which is cool, love the way it works if your using HTTPS), but if you are running central admin on HTTP there appears to be some issues in its logic. The code I'm looking at is [here](https://github.com/PowerShell/SharePointDsc/blob/dev/Modules/SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1#L569), but the issue is that if you try any of these combinations of settings you can't get it to show a pass on the test-resource:

_Scenario 1_
CentralAdministrationUrl="http://custom-name.domain.com"
CentralAdministrationPort="80"

Result = Error message when running set, Invalid Port (which comes from SharePoint itself, not DSC so lets call this one expected behaviour but it means I can't run central admin on my own custom URL this way)

_Scenario 2_
CentralAdministrationUrl="http://machine-name"
CentralAdministrationPort="9999"

Result = Set runs, test returns false - failing on the CentralAdministrationUrl not matching, get returns http://machine-name:9999, which led to me trying scenario 3

_Scenario 3_
CentralAdministrationUrl="http://machine-name:9999"
CentralAdministrationPort="9999"

Result = Error, don't specify the port in CentralAdministrationURL

#### Suggested solution to the issue

The solution needs to be that at a minimum if there is an error saying "Don't specify the port in the CentralAdministrationUrl" property, the get method shouldn't return it with a port either - which would stop the breaking behaviour and mean that scenario 2 becomes the approach that works. I can still use SPAlternateUrl to add my own custom URL to central admin (which is what I've always done anyway) so I'm not super fussed about this - but I wanted to capture it here incase anyone else hit it, so we can get the behaviour adjusted.

#### Version of the DSC module that was used ('dev' if using current dev branch)

dev

**Comment by ronx** [comment]
Hey @BrianFarnhill , thanks for the detailed test scenarios and explanation. Very helpful! I'll take a look at this later this afternoon and try to get some fixes in quickly. Cheers!

**Comment by ronx** [comment]
BTW - CentralAdministrationUrl was added specifically to support HTTPS implementation, but I was thinking that it could also be used for HTTP in the future. When I implemented it, I was thinking it would be ignored unless it was an HTTPS URL. Glad you jumped on it and identified the errors to keep it on the radar while it's all still fresh ;) ... 

Quick question for you @BrianFarnhill . When you use SPAlternateUrl to set the custom hostname, does it get wiped out if you run psconfig_ui.exe all the way through on the CA server? Unlike psconfig.exe, which doesn't reprovision CA every time you run it, psconfig_UI.exe can be a bit intrusive in that regard. If you have a lab setup this way, would you mind trying that and then checking the bindings in IIS to see if they're still intact? Also, double check AAMs after psconfig_UI. Thanks!

**Comment by BrianFarnhill** [comment]
@ronx I don't think I've run the UI config tool in about the last 5 years, so I actually don't know! It's a good point. If I'm running DSC regularly and it blows away the admin AAM then DSC will put it back, but it's worth kicking the tyres on a little to validate that scenario as well. I'll have a look over the next day or two and let you know how it behaves.

**Comment by ronx** [comment]
Yeah, SP2016 improved psconfig_ui tremendously, throwing in an automatic Get-SPProduct -Local across the board to avoid the common erroneous version mismatch error among other improvements. IMHO, 2016 made the UI config relevant to professionals again ;). But it also still reconfigures CA on every run when it shouldn't. Usually doesn't matter, but since binding information seems to be persisted in some hidden locations that are hard to set properly, especially with CA, reconfiguring often hijacks your bindings.

Also, most folks using DSC to install and configure SharePoint have set their farm servers' LCM ConfigurationMode to ApplyOnly, so if psconfig_ui hijacks their bindings, they will have to manually run Start-DscConfiguration again to have DSC fix up their bindings again. In fact, I bet only a very, very small percentage are running in ApplyAndAutoCorrect, so at best, their LCM's are logging the deviation to the event log and no one is monitoring.

Now, while I'm on my soapbox, the better solution would be for the PG to add proper support to (New|Set)-SPCentralAdministration, but then again, I certainly understand how far down the priority list these things are pushed if the PowerShell cmdlet noun doesn't match Msol*. ;)

**Comment by BrianFarnhill** [comment]
@Ronx Yeah I agree - if the psconfig UI does change the URLs though there might not be any other options that to let DSC either fix it (or at worst tell you about it if you're in ApplyAndMonitor). Other than us documenting it as a known thing in our docs on the wiki maybe - I think there's not a whole lot of other options in there for us. So if we just fix the output of the get method so our tests can pass with the local URL and then use alternate URL to set the CA HTTP url I think that's about all we can do realistically for right now. Do you think that's a fair assessment? Happy to hear other thoughts but I think that's about where we are at with it.

**Comment by ronx** [comment]
I think that at a minimum, we document that CentralAdministrationUrl should only be used for HTTPS and the Get method would throw an error if someone passed in an HTTP URL. In other words, if using HTTP, you would still have to accept the default http://<servername>:<port> for CA. Does the documentation/wiki already have an example of how to use SPAlternateUrl to update the CA binding with a vanity host?

**Comment by BrianFarnhill** [comment]
@ronx thats fair for an initial solution. I'll finish my config up that does the alternate URL config and post it here so that one of you guys can get it updated on the wiki seeing as I don't have permissions to this repo any more :P

**Comment by BrianFarnhill** [comment]
@ronx OK so I just ran the config wizard, here is a run down of what I did in the setup:

1. Add an "intranet" zone AAM to the central admin site (if you try to update the default one it makes a couple of other resources a little trickier, so I keep it seperate)
2. Add xWebsite with BindingInfo on the servers that run central admin so that I listen on both :9999 and spadmin.domain.com:80 for the central admin site
3. Use SPServiceInstance to make sure central admin is running on those servers I expect CA to run on
4. The central admin URL registry setting is updated to my custom URL so the start menu shortcut directs you to the custom domain name

After this I run the config wizard UI to see what breaks, the status afterwards was:

1. The intranet AAM was still present, so this is fine
2. The bindings I added to IIS were removed and it went back to only listening on :9999 
3. The central admin service was still running where it should have been running
4. The registry setting appears to stay at my custom value

What I can tell the only thing that breaks when you run the wizard is the IIS bindings, not the AAM mappings - which is still bad (especially if you're doing SSL since it'll take out the cert bindings too). 

So to be clear about how we do this going forward:

1. Update SPFarm to throw an error if you give central admin URL as a property with a URL that isn't HTTPS (for now, I think longer term we can actually make this work well with a HTTP path so then it's easier for people to use custom URLs without HTTPS if thats what they want to do, but if this was my project I would probably leave that as a low priority work item ;) ) 
2. We add some doco to the wiki that captures how to do a custom URL with HTTP using the approach I have below, and include wording to the effect of "If you run psconfig_ui.exe then you will lose your bindings, so run your DSC config again after or things will be broken"

The config I use for this looks like this (just the resources in question, not the whole thing):

        $runCA = $true
        if ($Node.NodeName -eq "wfe") {
            $runCA = $false
        }

        SPFarm CreateSPFarm
        {
            Ensure                    = "Present"
            DatabaseServer            = '${SPDatabaseName}'
            FarmConfigDatabaseName    = '${GenerateUsernames.db}_Config'
            Passphrase                = $Passphrase
            FarmAccount               = $FarmAccount
            PsDscRunAsCredential      = $SPSetupAccount
            AdminContentDatabaseName  = '${GenerateUsernames.db}_AdminContent'
            RunCentralAdmin           = $runCA
            IsSingleInstance          = "Yes"
            DependsOn                 = "[Script]SQLPermissions"
        }

        if ($Node.NodeName -eq "farm") {
            SPAlternateUrl CentralAdminAAM
            {
                WebAppName           = "SharePoint Central Administration v4"
                Zone                 = "Intranet"
                Url                  = 'http://${DNSPrefixCentralAdmin}.${DomainDNSName}'
                Ensure               = "Present"
                PsDscRunAsCredential = $SPSetupAccount
                DependsOn            = "[SPFarm]CreateSPFarm"
            }

            xDnsRecord CentralAdminDns {
                Name                 = '${DNSPrefixCentralAdmin}'
                Zone                 = '${DomainDNSName}'
                Target               = '${AdminLoadBalancer.DNSName}'
                DnsServer            = '${DNSServerIP}'
                Type                 = "CName"
                Ensure               = "Present"
                PsDscRunAsCredential = $domainAdminCredential
                DependsOn            = "[SPAlternateUrl]CentralAdminAAM"
            }
        }

        Registry CentralAdminLinkUpdate {
            Key       = "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Shared Tools\Web Server Extensions\16.0\WSS\"
            ValueName = "CentralAdministrationURL"
            Ensure    = "Present"
            ValueData = 'http://${DNSPrefixCentralAdmin}.${DomainDNSName}'
            ValueType = "string"
            DependsOn = "[SPFarm]CreateSPFarm"
        }

        if ($Node.NodeName -eq "app" -or $Node.NodeName -eq "farm") {
            xWebSite CentralAdminBindings {
                Ensure = "Present"
                Name = "SharePoint Central Administration v4"
                State = "Started"
                BindingInfo = @(
                    MSFT_xWebBindingInformation
                    {
                        Protocol = "http"
                        Port     = 80
                        HostName = '${DNSPrefixCentralAdmin}.${DomainDNSName}'
                    }
                    MSFT_xWebBindingInformation
                    {
                        Protocol = "http"
                        Port     = 9999
                    }
                )
            }
        }


@ronx are you able to do a PR to add that error on http or do you want me to try to get one in for it? @ykuijs whats the ETA on the 3.4 drop? I think this catch needs to go in on that to head this off from other people trying to do what I did with it (your call though)

**Comment by ronx** [comment]
@BrianFarnhill I just submitted the PR. I talked to @ykuijs earlier and the 3.4 cutoff was Wednesday. When the PR is merged, would you mind pulling dev and testing it out on your lab to see if it works as expected? I'll look into the possibility of hitting the stretch goal of supporting custom hostnames with http in the meantime for the 3.5 release, but I don't know how much demand there is for that. I would think the same method removing the web app and recreating with New-SPWebApplicationExtension would work for HTTP as well. But we might have to make assumptions, like whether the user intends to replace the Default zone AAM or add it using the Intranet zone AAM like you did and leave the default binding in place. When we're aiming for HTTPS, it's easier to assume that we can replace the default HTTP binding because we're making the admin application more secure and want to close up the non-secure binding. But with HTTP, we're primarily doing it for cosmetic reasons, or possibly to point to a load balancer instead of a specific server, or just to obfuscate the server name. Let me know if you have any opinions on what assumptions we could make and what we should consider giving the option for.

**Comment by BrianFarnhill** [comment]
@ronx I agree, don't sweat the HTTP support at all. I'm only looking at it so I can use a load balancer, which I think is a common enough scenario - but given HTTPS is a preferred practice I wouldn't go out of your way to support HTTP, especially given that it can work with the config I've got there. I would say that feature would be a nice to have, definitely not mandatory though. I'll run the development branch through my lab next week and confirm that it's all fine though and let you know. Thanks bud.

**Comment by ykuijs** [comment]
PR #1066 is merged. Reopening this issue, since it isn't 100% fixed yet.

**Comment by ronx** [comment]
@ykuijs The "bug" is fixed, right? The meta has been updated to provide info about how CentralAdministrationUrl is only for HTTPS, and an exception is now being thrown when an HTTP URL is passed. So we're now purposefully handling those scenarios instead of letting them happen and then failing as an unexpected error.

By it being not 100% fixed, are you referring to it being able to support HTTP as well? If so, do you think we should track that as a new enhancement instead of it being part of this bug?

**Comment by ykuijs** [comment]
@ronx That is correct. Could you please create the new issue?
