### ISSUE TITLE
Language Packs

### ISSUE THREAD

**Issue by tonyhxh** [PowerShell/SharePointDsc#217]
Hello, Brian:

Is there a plan to install language pack, and create a Resource Module called, say "xInstallLanguagePack"?

Thanks
Tony Huang from GM

**Comment by BrianFarnhill** [comment]
Hi @tonyhxh 

I'll put this in to our backlog to look at. I've not scripted the install of a language pack before but it may even be possible to use the [Package resource](https://msdn.microsoft.com/en-us/powershell/dsc/packageResource) to do this instead of a custom one in xSharePoint. I'll have a look in to this and let you know how we get on.

 \- B

**Comment by tonyhxh** [comment]
Package probably can do the job. We will give a try. Thanks

**Comment by BrianFarnhill** [comment]
I'll leave this one open until we can investigate and confirm. Thanks @tonyhxh

**Comment by magnustomte** [comment]
Hi
You can install the binaries using Package, but you still need to configure SharePoint. Otherwise you will get "Upgrade Required" (although running stsadm -o localupgradestatus shows 0 pending upgrades).

The reason for this is that when installing the language packs, the installer sets HKLM:\SOFTWARE\Microsoft\Shared Tools\Web Server Extensions\*\WSS\LanguagePackInstalled to 1. This is discusessed here: https://social.technet.microsoft.com/Forums/en-US/11f370ef-be03-4eac-83af-9dc6ba942d3e/can-i-skip-psconfig-if-i-installed-a-language-pack-before-creating-a-farm?forum=sharepointadminprevious

I am using SharePoint 2013, and created a quick and dirty resource for this which basically runs psconfig if LanguagePackInstalled is set to 1:
```
function Get-TargetResource
{
	[CmdletBinding()]
	[OutputType([System.Collections.Hashtable])]
	param
	(
		[parameter(Mandatory = $true)] [boolean] $LanguagePackInstalled,
		[parameter(Mandatory = $false)] [System.Management.Automation.PSCredential] $InstallAccount
	)

	$NeedConfigure = [int](Get-Item -Path 'HKLM:\SOFTWARE\Microsoft\Shared Tools\Web Server Extensions\*\WSS\').GetValue("LanguagePackInstalled")

	Write-Verbose "LanguagePackInstalled parameter set to $NeedConfigure"

	return @{
		LanguagePackInstalled = [boolean]$NeedConfigure
		InstallAccount = $InstallAccount
	}
}

function Set-TargetResource
{
	[CmdletBinding()]
	param
	(
		[parameter(Mandatory = $true)] [boolean] $LanguagePackInstalled,
		[parameter(Mandatory = $false)] [System.Management.Automation.PSCredential] $InstallAccount
	)

	$result = Invoke-xSharePointCommand -Credential $InstallAccount -Arguments $PSBoundParameters -ScriptBlock {
		$params = $args[0]                                      

		Write-Verbose "Running PSConfig to configure language pack(s)"
		$PSConfig = (Get-Item -Path 'C:\Program Files\Common Files\microsoft shared\Web Server Extensions\*\bin\PSCONFIG.EXE').FullName
		Start-Process -FilePath $PSConfig -ArgumentList "-cmd upgrade -inplace b2b -wait -force" -NoNewWindow -Wait
	}
}

function Test-TargetResource
{
	[CmdletBinding()]
	[OutputType([System.Boolean])]
	param
	(
		[parameter(Mandatory = $true)] [boolean] $LanguagePackInstalled,
		[parameter(Mandatory = $false)] [System.Management.Automation.PSCredential] $InstallAccount
	)

	$CurrentValues = Get-TargetResource @PSBoundParameters

	if ($null -eq $CurrentValues)
	{       
		return $false 
	}

	return !$CurrentValues.LanguagePackInstalled
}

Export-ModuleMember -Function *-TargetResource
```

**Comment by BrianFarnhill** [comment]
@magnustomte That's great. I might try to add a "ScheduleWindow" option to this as an optional parameter for people that don't want that running just whenever as it will cause a brief outage - but other than that thats a great start that we can use. I'll make sure this gets picked up and put in.

Do you have an example of how you used the Package resource to install the language pack? We can work that in to the documentation to make sure people know how to do it (and if you've got it then it saves me putting it together! :P)

**Comment by ykuijs** [comment]
Installation of a language pack is the same process as installing a service pack or CU. Install binaries and then run the config wizard. We might consider creating a generic resource to install these types of components, but we already discussed installing updates in the past :-)

Language packs also have their own service packs, however CU's are multi-lingual. Just like with the SharePoint install, you can slipstream updates into the language pack by extracting them and copying the folders into the Updates folder of the setup package. (Although you can debate if it is a good idea to slipstream CU's, since they are multi-lingual :-))

**Comment by BrianFarnhill** [comment]
@ykuijs Yea I'm imagining that this would be a generic "run upgrade" resource kinda thing, so not something specific to the CU but it would help with the installation. Which does loop us back around to that upgrade discussion about how we do it. I think a resource like this would be a good step in the right direction in terms of addressing both patching and language packs

**Comment by magnustomte** [comment]
@BrianFarnhill The process of installing the language pack is (as @ykuijs points out) the same as SPs or CUs. The technical procedure would be the same as for xSPInstall; mount the img file, generate a config.xml file, and call setup.exe /config config.xml. To do this with the Package resource would require you to have everything set up, i.e. the img mounted and the config.xml already in place. I have not done this myself, but it would be something like:

```
Package SharePointLanguagePack
{
	Ensure = "Present"
	Name = "SharePoint Language Pack"
	Path = "C:\Install\SPLanguagePack\setup.exe"
	ProductId = ''
	Arguments = '/config config.xml'
}
```

**Comment by BrianFarnhill** [comment]
I'm tagging this one as in progress as I know @ykuijs is leading up the work in this space

**Comment by ykuijs** [comment]
No that PR391 is closed, this one can be closed.
