### ISSUE TITLE
TypeName in Service Application resources should not use localised strings

### ISSUE THREAD

**Issue by BrunoReboul** [PowerShell/SharePointDsc#342]
**Context:** Windows Server + Language Pack

**Symptom:** Set works, then Test fails, triggering a new Set that end up in error

**Why:** Get function have English Sharepoint name hardcoded. As Sharepoint on a localized OS send back service names in the local language the DSC test functions wrongly determine Ensure as "Absent" while it should be "Present"

**Proposed fix** : update resources to rely on the Object model instead of the TypeName to identify SharePoint Services / objects.

**Comment by BrianFarnhill** [comment]
@BrunoReboul I'm not sure I follow exactly what you are referring to here. Can you let me know which resources you are seeing this in? is this about the "Type Name" in the service app resources? Or something else? If you could include some examples of the output you are seeing that is breaking this then we can investigate

**Comment by luigilink** [comment]
Hi Brian,
I can give you some details because we have the same customer ;)
We have this issue with the MSFT_SPServiceInstance resource

- La ressource DSC PowerShell MSFT_xSPServiceInstance n'a pas pu exécuter la fonctionnalité Set-TargetResource. Message d'erreur: Unable to locate service application 'Managed Metadata Web Service'

- La  ressource DSC PowerShell MSFT_xSPServiceInstance n'a pas pu exécuter la fonctionnalité Set-TargetResource. Message d'erreur: Unable to locate service application 'Secure Store Service'

**Why:**
The Cmdlet Get-SPServiceInstance returns a mix of French and English TypeName, because the French LP is installed on Windows2012.

**Solution:**
Like AutoSPInstaller, get the service Instance with gettype() method :
`$secureStoreServiceInstances = Get-SPServiceInstance | ? {$_.GetType().Equals([Microsoft.Office.SecureStoreService.Server.SecureStoreServiceInstance])}`

**Disadvantage:**
Each Type must be defined instead of using the TypeName. Not impossible but a lot of modifications will be needed for this resource

**Comment by BrianFarnhill** [comment]
@luigilink Ahhhh - yep, makes perfect sense. I'll put this on the backlog to be resolved. I don't think it'll be too big of an effort, it can (and should) definitely be done though. Thanks for the info!

**Comment by luigilink** [comment]
Fix proposal in this pull request #350
