### ISSUE TITLE
Add xSPSecureStoreApplication resource

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/SharePointDsc#35]
The xSPSecureStoreApplication resource is used to create entries in the secure store service application. It should be structured as follows:

xSPSecureStoreApplication MySecureAccount
{
    SecureStoreServiceApp = "Secure Store Service Application"
    Ensure = "Present"
    Name = "MySecureCredential"
    DisplayName = "My secure credential"
    ContactEmail = "someone@contoso.com"
    TartgetAppType = "Individual"
    UrlType = "Default"
    CredentialOwner = "CONTOSO\someone"
    CredentialToStore = $CredentialToStore
}

**Comment by mrpullen** [comment]
What properties should the UrlType accept?

Also what's the plan to capture fields in the Secure Store Application. We can store all sorts of things in Secure Store Target Application, there are like 6 different field types (Key, Generic, Username, Password, WindowsUsername, WindowsPassword).

For the Fields how about an array of objects like the following
@{
Name : STRING
Type (ValidateSet "Key", "Generic", "Username", "Password", "WindowsUserName", "WindowsPassword")
Masked (ValidateSet "True", "False")
Credential: PSCredential
Value:
}

Then the logic would be if you were passing a WinodwsPassword or PAssword field to resolve it from the PSCredential.Password, for WindowsUSerName, or Username resolve from PSCredential.Username, otherwise for Generic or Key use the Value field.. (Maybe use "Masked: true | false but passing a PSCredential for everything might be a pain).

Anyway this is my first contribution to GitHub, so it might be slow going, but I need this functionality, so seems like a good place to start.

**Comment by BrianFarnhill** [comment]
Hey MrPullen,

That sounds like a sound approach as a starting point. One thing that I got pinged on in regards to secure values is that we need to be mindful of making sure they get encrypted in the MOF files, so an example of where we didn't do that was in the xSPSecureStoreServiceApplication, where we had database username and password as string values (because that's how SharePoint accepts them). So in the context of values we put in to the secure store we should be making sure that anything which should be getting treated as "secure" gets encrypted, which might mean using PSCredential for everything like you state there might need to be a consideration? 

Happy for you to have a crack at this and we can discuss what comes out as you go along - feel free to let me know your email address through the [contact form on my blog](http://blogs.msdn.com/b/brian_farnhill/contact.aspx) and I'm more than happy to discuss this with you via email as well.

**Comment by camiloborges** [comment]
Hello
I might work on this one.
Notes:
Needs to support: 
1) update key: https://technet.microsoft.com/en-us/library/ff607850.aspx
2) Applications, and Fields: covered on Update-SPSS https://technet.microsoft.com/en-us/library/ff607985.aspx

it sounds like this will become another complex module.

**Comment by jmcanally** [comment]
I'm currently working on this one and planning to submit my changes this week.  So far I have the basics working following the guidance mentioned in previous comments.

**Comment by BrianFarnhill** [comment]
Tagged as in progress, its all yours @jmcanally

**Comment by ykuijs** [comment]
Resource created: SPSecureStoreServiceApp
