### ISSUE TITLE
Sharepoint now support install on .Net 4.6 - Update SPInstallPrereq

### ISSUE THREAD

**Issue by AlexandrosIV** [PowerShell/SharePointDsc#403]
With the following fix, now SharePoint can be installed on servers running .Net 4.6, but the SPInstallPrereq is checking against and halting the installation.

the check need to be removed or improved.

[SharePoint 2013 installer now supports .NET Framework 4.6 and above](https://blogs.technet.microsoft.com/stefan_gossner/2016/09/14/sharepoint-2013-installer-now-supports-net-framework-4-6-and-above/)

**Comment by BrianFarnhill** [comment]
OK so looking at this one the hotfix involves downloading and modifying the installation files themselves, so we can't search for a specific hotfix to be installed on the system as it won't be there. Looks like if we are going to detect this we need to go looking for svrsetup.dll or wsssetup.dll in the updates folder and to then make sure it is at least build number 15.0.4709.1000 (or higher) to make sure that the fix is there. Shouldn't be too hard to work that in to the test logic if we detect a higher version of .NET. If it fails we can then direct them to the specific hotfix rather than let that generic error about .NET not being installed be what falls out.

Thanks for reporting this @AlexandrosIV - we'll get it implemented when we can.

**Comment by ykuijs** [comment]
Working on it!

**Comment by ykuijs** [comment]
@BrianFarnhill, Issue can be closed. Is fixed in PR415
