### ISSUE TITLE
Does not work via Puppet dsc

### ISSUE THREAD

**Issue by riponbanik** [PowerShell/SharePointDsc#463]
When running through puppet dsc -version 1.2.0 it complains that 1. Could not evaluate: The term 'Invoke-SPDSCCommand' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name , or if a path was included, verify that the path is correct and try again.

**Comment by BrianFarnhill** [comment]
OK, so knowing nothing at all about puppet, troubleshooting this one should be interesting - but here goes :) 

So that Invoke-SPDSCCommand function is one that is published by the main module, so in theory as long as the SharePointDsc module is published in one of the module directories that PowerShell recognises then it should be able to be found. The quick way to test this is if you open a normal powershell window and type "Invoke-SPDSCCommand" and see if it tries to run the command or not. So lets try that for a starting point and we can start working it out from there. 

I'm pretty sure it should work with Puppet - I know a few customers who are using Chef with these resources and from what I understand the two call PowerShell DSC Resources in similar ways, so lets try that and see what we can come up with.

**Comment by johlju** [comment]
I might be wrong here, but I think Chef uses the resources but Puppet "converts" them to puppet code. But I could be wrong. But if it converts then maybe the external modules does not he converted. 
I'm curious how this works using SharePointDsc in Puppet. :)

**Comment by BrianFarnhill** [comment]
@riponbanik Were you able to validate that you could run the Invoke-SPDSCCommand in a normal powershell window without importing the module?

**Comment by riponbanik** [comment]
@BrianFarnhill thanks for the follow up. I will start over, will update you

**Comment by BrianFarnhill** [comment]
@riponbanik Hey there, did you get around to testing that command?

**Comment by BrianFarnhill** [comment]
Given that this one hasn't been responded to since early Feb I'm closing it off. If we get more comments on it I'll re-open it to continue investigation
