### ISSUE TITLE
New Resource SPWarmUp

### ISSUE THREAD

**Issue by luigilink** [PowerShell/SharePointDsc#474]
A new resource I'm working on.
With this resource, we can warmup all site collection of all web application.

PR in progress #475 
Is it a good idea to have this resource ?

**Comment by BrianFarnhill** [comment]
I like the idea of making it easier to include a warmup script, but I'm not 100% convinced inside an actual DSC resource is the place for it. When you look to categorise this it's not really "configuration", it's more an ongoing maintenance task per se, if that makes sense, which is why I have a bit of an objection to it in the form you have submitted. If you look at your code your test method is essentially the thing that is triggering things, it's not indicating if the system is in the desired state - although I can see there being an argument for "the desired state is to make sure the app pool is running" but if that's the case we need a mechanism to test if it's running or not (so things like Test-DscConfiguration won't trigger changes, they will just report on state).

In my current customers I actually just deploy a warm up script to each server using the File resource, and then I use xScheduledTask from [xComputerManagement](https://github.com/powershell/xcomputermanagement) to be able to schedule the warm up to run every 15 minutes or whatever interval you want. Then from a DSC perspective we are ensuring that the scheduled task exists and is configured correctly, and the actual work of doing the warm up just sits inside that script, so I think that makes a lot more sense from a DSC perspective.

That said, I don't hate the idea of including something in SharePointDsc for this seeing as pretty much everyone does this for every SharePoint environment - I just think we need to rethink the approach. We can either document the xScheduledTask approach in the wiki or something so people have a reference for how to implement it, or we can chance SPWarmUp to behave a little more like that where it is responsible for deploying a scheduled task that is preconfigured to do the warm up work, then we just test for the task in the test method, and the set method updates the task. So the only real difference from xScheduledTask will become that we will hard code the parameters to call powershell.exe with a script inside of our module, otherwise the rest of the logic can be pretty much the same. 

Thoughts on this anyone? @ykuijs ?

**Comment by MikeLacher448** [comment]
I like Brian's method of having a resource that deploys the script and scheduled task, but runs it as part of the scheduled task, not as part of the configuration.

**Comment by ykuijs** [comment]
Agree with you, Brian. I don't think DSC is the right place for a warmup script.

I am a bit divided between your two ideas:
- Documenting the method to use the other resources to deploy and configure the script sounds good, but means we have to keep checking our documentation for changes in the other resources.
- I like the idea to create a resource to fully automate the deployment and configuration of  the script from SharePointDsc, but this basically means reimplementing (and maintaining) functionality of xScheduledTask in this resource.

At this moment I am not sure which approach I prefer, but I tend to go for the first option.

**Comment by luigilink** [comment]
Totally agree with you, I'll close the PR #475

**Comment by ykuijs** [comment]
Closing issue, since the decision was to not use DSC to implement this functionality
