### ISSUE TITLE
SingleServer installation type

### ISSUE THREAD

**Issue by tonyhxh** [PowerShell/SharePointDsc#489]
Hello, Brain:

I am Tony Huang from GM, and we probably talked on a phone call before. 

Recently we noticed some of our SharePoint servers built from SharePointDSC (ModuleVersion = '1.2.0.0') cointain installation type "SingleServer"

It's registry value called "ServerRole" which is located at:  \HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Shared Tools\Web Server Extensions\16.0\WSS

We know we didn't feed module SPCreateFarm and SPJoinFarm "singleserver" minrole, but how could it happen?

Please let me know if you've seen it before.

Thanks
Tony Huang

**Comment by BrianFarnhill** [comment]
Hi @tonyhxh 

Sorry for the late response, had to do some homework and testing here. From what I understand this is actually nothing to do with MinRole and is something to do with how SharePoint was installed. It's actually been in the product for a few versions (at least from 2007 forward from what I can find) and is to do with the installation option you choose when setting it up. 

There is an option when you run through the GUI installer that lets you choose either "Single Server" or "Web Front End" I believe it is (the wording and options on these have changed a little from version to version, its essentially been "single server" or something else at each version) and this alters what binaries get installed on the server a little. So this has nothing to do with MinRole or how you created or joined servers to the farm.

Can I ask how you did the installation of the binaries in this environment? If you did it with SPInstall as a DSC resource then this registry key should read "APPLICATION" because that is what we hardcode the config to in the [SPInstall resource](https://github.com/PowerShell/SharePointDsc/blob/dev/Modules/SharePointDsc/DSCResources/MSFT_SPInstall/MSFT_SPInstall.psm1#L175). 

I believe the install must have been done manually using the single server option at this point of the configuration, so this isn't an issue with DSC at all. Can you confirm how the binaries were done?

 - B

**Comment by alistairl** [comment]
This is interesting - I've just built an environment a few times using Azure IaaS and DSC Configuration that uses SPInstall against a folder structure with the January 2017 update and the registry keys are showing SingleServer. It looks like this may hold up deployment of a search topology.

**Comment by BrianFarnhill** [comment]
OK so I've got a farm that I build using DSC in Azure (using my own pull server, not the DSC extension - shouldn't make a difference but lets list out everything here) that was built to 16.0.4456.1000 (so the November update pack - Feature Update 1, where we added the extra MinRole roles) and it shows Application still. Now, my gut is still telling me this is very unlikely to be a DSC issue, so the different patch levels interest me, but lets find some evidence and work it from there.

@alistairl - Are you able to get me a copy of the SharePoint installation logs that got used for your install that is showing the singleserver bit? It should be at C:\windows\temp if you didn't specify a PsDscRunAsCredential option on that SPInstall resource. Otherwise it'll be in the temp path for the user that you ran it as. If you could email it to me that would be great (my email is just my firstname and lastname with a dot between it, at microsoft.com) I'll see what was in there to determine if it used the config file we created or if it fell back to something else.

**Comment by alistairl** [comment]
I've emailed the install log across. I'm going to tear the environment down and check the install status as I go.

**Comment by BrianFarnhill** [comment]
@alistairl  OK so looking at the logs you sent me, I can 100% verify that the server is being installed correctly as per this line:

> 2017/03/31 09:34:56:042::[2312] Parsed setting: SERVERROLE with value: APPLICATION in config.xml.

You can follow the SERVERROLE property through that log file and see that it stays at application the whole way through, so the issue isn't with how we are installing via DSC (unless someone can show me a log file that proves otherwise). 

As per @alistairl email to me though, there was suggestion that the change happened after the servers joined the farm, which to me sounds like a bug in the product. I checked my environments for this and I didn't see it, multiple servers all stayed at APPLICATION as I set up the farm. I know he is looking in to that though so if we can validate that behaviour we can look at getting a support ticket open to look at that. So lets keep working the logs and seeing what we can pull out and isolating the point that it gets changed to SINGLESERVER from there.

**Comment by alistairl** [comment]
@BrianFarnhill my latest strategy is to examine the impact of the update on the farm due to that being one difference between your and my test environments. I'll build from RTM, patch to November and see the results from that.

**Comment by ykuijs** [comment]
Is this issue still occurring? In other word: Do we have to leave it open or can it be closed?

**Comment by NikCharlebois** [comment]
@ykuijs we should most likely close that one. I've not been able to replicate it with any of the latest builds.

**Comment by ykuijs** [comment]
Agree, also since we didn't a reply on the last ask for a statusupdate from @tonyhxh.

Please reopen the issue if the issue still occurs.
