### ISSUE TITLE
Improve error message in SPBlobCache where web role isn't present

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#502]
**Details of the scenario you try and problem that is occurring:**
I guess this is a question more than an issue.

Calling the Get-TargetResource function of the MSFT_SPBlobCacheSettings resource from a server that is not a Web Front-End throws an error. It complains that it can't find the web.config file for given Web Applications. Could the resource accept a server name and do a remote check on the given machine to see if the web.config file exists (this is similar to my DistributedCache request). 

I don't want these requests to have a major impact on the "Forward" DSC just for the sake of making things work for the ReverseDSC. However, the intent for reverse DSC at this point is to simply have the SharePointDSC module installed on one server in the farm, the server we run the reverse process from. If ReverseDSC is to take care of making the remote call to all servers to retrieve the local Get-TargetResource info, then that would require the same module version to be installed on each node.

So the question is, shoud the Get-TargetResource be responsible to make remote calls to "direct methods" (e.g. read web.config content) remotely based on a "ComputerName" param, or should it only retrieve local information for that one server, and let the ReverseDSC remotely call all the Get-TargetResource methods?

**The DSC configuration that is using the resource:**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Win 2012 R2 / WMF 4

**Version of the DSC module you're using:**
1.5.0.0

**Comment by BrianFarnhill** [comment]
@NikCharlebois I don't think we are going to do these types of remote checks at all, since the intent of the actual resources themselves is to focus on the node in question. So I think there is potentially a better error message for us to show here to explain why it can't return the current settings, but doing a remote check is not something I want to bake in to the resources here. @ykuijs your thoughts mate?

**Comment by ykuijs** [comment]
I agree on the cross server suggestion, however I think we should extent the current resource a bit:
As Nik indicates, you can run this resource against a server which does not have the web role running. The resource then fails because it cannot find the web.config file. I think it would be nice to first check if the server has the web role and if not throw a meaningful error.

**Comment by BrianFarnhill** [comment]
Done, I've updated the name on this issue to reflect the change that we need to make and tagged it appropriately

**Comment by ykuijs** [comment]
I am on it, will be fixed in a bugfix PR

**Comment by BrianFarnhill** [comment]
This has been merged to dev and will ship in our next release, closing this issue
