### ISSUE TITLE
DatabaseServer value of Get-TargetResource with Alias

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#528]
**Details of the scenario you try and problem that is occurring:**
This is affecting all of our Resources that return a database server value as part of their Get-TargetResource method. If the DB is located on a server with an alias, only the server's name is returned and not the actual alias.

I have currently setup a continuous integration pipeline in Azure, that keeps ReverseDSC'ing an existing environment, wiping it off, then running the extracted script to recreate environment using the Forward route. All my Service Applications are failing to get recreated because of this issue. 

Can we ensure the full name of the DB server including the alias is returned by the Get-TargetResource? 

**The DSC configuration that is using the resource:**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Win 2016 / PoSh 5.1

**Version of the DSC module you're using:**
1.6.0.0

**Comment by BrianFarnhill** [comment]
As far as I know (and I'm happy to be corrected here) when you use SQL client aliases SharePoint doesn't even know it's dealing with an alias. You just give it a "server name" and that name will either be a normal server name (or FQDN) that will resolve to the IP address of the server through a standard DNS call, or you'll give it an alias so that the SQL pipeline can swap in the new value of the server name before that DNS call gets made, effectively redirecting it. What that means is that in terms of what SharePoint knows about, it just has the name of a server - it could be a server name or it could be an alias, but SharePoint doesn't know or care, it's the SQL Connection pipeline that handles the alias bit.

What all that means is that whatever comes out of the database server name properties is going to be what SharePoint thinks its connecting to. How that actual connection happens is something that goes on outside of SharePoint per se. So my question to you here is are you seeing this behaviour, or are you seeing/expecting something different to this?

**Comment by NikCharlebois** [comment]
What I am seeing is that if SP is configured on an alias, say CorpSQL\SPDev, when caling the get-targetresource of Get-SPFarm for example, all we get back as server name is "CorpDev". However when I originally configured that SPFarm resource, I had to pass in the full "CorpSQL\SPDev" name as DatabaseServer. Again, this doesn't really affect the "Forward" DSC route at all, but has an impact on the "Reverse" one. 

Am I being too philosophical here if I state that in my opinion "For a DSC module to fully compliant, it needs to include logic that will allow environments to self-onboard themselves onto DSC. Meaning that if a component of an existing environment is not yet using DSC, you should be able to onboard it by passing the output of its Get-TargetResource directly into its Set-TargetResource?"

In our case, if the Set-TargetResource expects "CorpSQL\SPDev" as the DatabaseName, then its Get-TargetResource should return that exact value.

Thoughts?

**Comment by ronx** [comment]
Hey Nik, I must've missed this thread when I searched the issues log before reporting the same thing a few months ago. See #638 . @ykuijs is working on a large PR (that I believe he just submitted) that will include the fix, changing SPDatabase.Server.Name to SPDatabase.NormalizedDatasource. This should fix the value returned for aliases and named instances. I haven't seen the pull request yet, but there should be 15 resources updated. @ykuijs , does that sound about right?

**Comment by ykuijs** [comment]
@ronx The PR indeed includes this fix for 15 resources.

**Comment by NikCharlebois** [comment]
A-W-E-S-O-M-E!

**Comment by ykuijs** [comment]
Closed with PR 660
