### ISSUE TITLE
SPManagedAccount Issue obtaining the instance

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#533]
**Details of the scenario you try and problem that is occurring:**
There is a bug in the Get-TargetResource method of the SPManagedAccount resource. The following line:

$ma = Get-SPManagedAccount -Identity $params.Account.UserName `

Users the Username property of the Account param. However, this param is optional. Instead it should use the mandatory AccountName property to retrieve the instance:

$ma = Get-SPManagedAccount -Identity $params.AccountName

This causes and issue where every single instance is being returned from the resource.

**The DSC configuration that is using the resource:**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Win 2012 R2/PoSh 5

**Version of the DSC module you're using:**
1.6.0.0

**Comment by ykuijs** [comment]
I am on it, will be fixed in a bugfix PR

**Comment by BrianFarnhill** [comment]
OK so looking at this there are a couple of issues here that I want to call out.

* Account shouldn't be optional, it should be mandatory. There is no way this resource works without it
* Account should probably be the key attribute here as well, rather than a duplicate string that we have

Now the way I see it, the first item there can go in to 1.x since it's something that should have been that way all along and we don't support it running without that property, so easy fix there. We need to make sure the get method returns a credential with the username on it (We do this for the crawler account in SPSearchServiceApp) but no biggy there.

The second item though is a definite breaking change and needs to hit the v2.0 pipeline after we test it. I don't know what happens when you use a complex type as a key property, but I think we need to give it a crack.

**Comment by BrianFarnhill** [comment]
This has been merged to dev and will ship in our next release, closing this issue
