### ISSUE TITLE
Access Denied with SPDesignerSettings

### ISSUE THREAD

**Issue by paugusto76** [PowerShell/SharePointDsc#587]
Using the ReverseDSC to generate a script from a Farm already installed and configured I get this resource configuration:

    $SetupAccount = Get-Credential -UserName "CORP\sp.setup" -Message "Credentials for CORP\sp.setup"

        SPDesignerSettings SiteCollection84a91272-e1b1-4f80-a1d6-efcda54e81b6
        {
            Url = "http://mysites.corp.contoso.loc";
            PsDscRunAsCredential = $SetupAccount;
            AllowSharePointDesigner = $True;
            AllowDetachPagesFromDefinition = $False;
            SettingsScope = "SiteCollection";
            AllowCustomiseMasterPage = $False;
            AllowCreateDeclarativeWorkflow = $True;
            AllowSavePublishDeclarativeWorkflow = $True;
            AllowSaveDeclarativeWorkflowAsTemplate = $True;
            AllowManageSiteURLStructure = $False;
        }

But when I start the DSC Configuration it gives me the following error:

PowerShell DSC resource MSFT_SPDesignerSettings  failed to execute Set-TargetResource functionality with error message: **Site collection not found. SharePoint Designer settings will not be applied**
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : AZREPLICA01

Which is strange because the site collection exists. Looking at the ULS logs I can see that no User Identity is passed in the request:

SPRequest.OpenWeb: UserPrincipalName=, AppPrincipalName= ,bstrUrl=http://mysites.corp.contoso.loc
System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))

Versions used:
Operating System: Windows Server 2016 (Version 1607)

PowerShell: 
PSVersion                      5.1.14393.206
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.206
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

SharePointDSC: 1.6.0.0

SharePoint 2016 (16.0.4456.1000)

**Comment by lazda** [comment]
Check if Setup account has access to root site collection. (because SettingsScope = "SiteCollection") 
In mysite scenario is better to set SPD Settings on WebApplication scope.

**Comment by BrianFarnhill** [comment]
Nope I see the issue here - if you go to [line 304 of SPDesignerSettings](https://github.com/PowerShell/SharePointDsc/blob/dev/Modules/SharePointDsc/DSCResources/MSFT_SPDesignerSettings/MSFT_SPDesignerSettings.psm1#L304) you see instead of doing this:

    Get-SPSite -Identity $params.Url

We have a Get-SPSite that uses a Where-Object to filter, which looking at it is totally the wrong approach. Firstly, the $Url variable won't exist in that scope (it should be $params.Url) and secondly when you have a large enough number of site collections Get-SPSite won't return them all (unless you have "-Limit All" on it) which means that our logic there won't pick up all sites to find them anyway, so realistically either of these issues could be causing your problem. The good news though is that this should be an easy bug fix.

@ykuijs Seeing as this should be a quick fix can you include this on your next roll up PR for me to review?

**Comment by ykuijs** [comment]
Done!

**Comment by ykuijs** [comment]
Fix included in PR 600
