### ISSUE TITLE
Renaming a Web Application

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#604]
**Details of the scenario you try and problem that is occurring:**
FEATURE REQUEST:
This ask came up after a session I delivered in Ottawa on SPDSC. Is there a way to make the SPWebApplication resource handle the scenario where we are trying to rename a Web Application? Maybe by providing an optional GUID parameter and detecting if the name in the config is different from the one currently assigned to a Web App with that GUID?

**The DSC configuration that is using the resource:**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
N/A

**Version of the DSC module you're using:**
1.6.0.0

**Comment by jar240** [comment]
Hi Nick. I was at your session and have been thinking about this.

I'm not sure a rename belongs in any DSC, because it is an operation, or a "way of achieving the desired state", not the actual desired state itself.

What do you think?

Thanks,
Chris

**Comment by NikCharlebois** [comment]
There may be cases however that are more of an "update" scenario than a "set". For example, if you have a service instance that is enabled, and then push a new dsc that mentions it as disabled, you need to perform the operation to shut it down. But I agree 100% with what you are saying. I believe that scenario falls right in the grey zone. I am not convinced we'll want to tackle this as part of the spwebapplication resource but wanted to have it logged.

**Comment by BrianFarnhill** [comment]
Yea this is a tricky one for us. Essentially what it boils down to is that we need a consistent "identifier" for each instance of each resource. In terms of the web app resource we decided the display name would be it since it was more likely the URLs would change than the display name property (based on it representing the intent of the web app vs a URL which might need to be updated). So updating the primary key kind of breaks the model in that its no longer representing that instance of a resource but a new one. Now we could have a chat about whether the URL or the display name should be the primary key (which would be a breaking change to implement) but I tend to agree with the approach we took here, so based on that I don't think this is an issue for DSC to solve. I think its something to be done manually or through a custom script and then update the DSC to reflect the new desired state.

@ykuijs you got any thoughts on this one?

**Comment by MikeLacher448** [comment]
I thought about this scenario before, and think it's just as easy to dismount content DBs, delete the web app, and push a new config with the new name and desired settings, and remount the content DBs.

**Comment by NikCharlebois** [comment]
@MikeLacher448 I don't think the challenge lies in the logic of making it happen as much as it lies in what other implications this would have. We picked the Web Application's Name as our primary key. In this scenario we are trying to update the primary key of an instance. I am just not sure we want to open this can of worms.

**Comment by BrianFarnhill** [comment]
@NikCharlebois and in lieu of any objection from @ykuijs I tend to agree, so I'm gonna close this one as a "won't fix" and leave it to be handled outside of the realm of DSC. Happy to re-open if anyone has a different perspective that will bring me around though.

**Comment by ykuijs** [comment]
Sorry guys, little busy the last few days :-)

Totally agree with these conclusions. Don't think this is a scenario which we should solve using DSC
