### ISSUE TITLE
SPManagedMetadataServiceApp sets incorrect defaults

### ISSUE THREAD

**Issue by wfeaser** [PowerShell/SharePointDsc#674]
The SPManagedMetadataServiceApp does not properly support the configuration of multiple MMS service apps.  When multiple service apps are configured, each will be set as the default for keywords and column specific term sets.  This leads to an error in CA when editing the MMS Connection (select service app proxy in CA and click "Properties").  To fix this issue, the New-SPMetadataServiceAppProxy logic in the resource (see below) should be parameterized to allow the configuration to control which MMS service app will be the default.

265             $app = New-SPMetadataServiceApplication @params  
266             if ($null -ne $app) 
267             { 
268                 New-SPMetadataServiceApplicationProxy -Name $pName ` 
269                                                       -ServiceApplication $app ` 
270                                                       -DefaultProxyGroup ` 
271                                                       -ContentTypePushdownEnabled ` 
272                                                       -DefaultKeywordTaxonomy ` 
273                                                       -DefaultSiteCollectionTaxonomy 
274             } 
275         } 

This issue is confirmed in multiple versions of SharePointDSC, including the "release-1.9" and "preview-2.0" branches.

Environment in which the issue was discovered:  SP2013, Windows 2012R2.

**Comment by BrianFarnhill** [comment]
@wfeaser Multiple instances of service applications was not something that was in our initial brief to provide support for, thus the behaviour you are seeing. That said, adding these parameters in shouldn't be too difficult so we'll put it on the backlog and see if we can get someone to code them up.

**Comment by ykuijs** [comment]
@wfeaser I believe this will be fixed is a large overhaul of the SPManagedMetadataServiceApp @andikrueger just submitted a PR for.

**Comment by ykuijs** [comment]
#666

**Comment by andikrueger** [comment]
@ykuijs I see a challenge with this setting being a part of the 'SPManagedMetadataServiceApp' resource.
If we set the DefaultProxyGroup and DefaultSiteCollectionTaxonomy in the 'SPManagedMetadataServiceApp' and if there is more than one usage of this resource available in the configuration, we would have to change all other resources prior to this one. Testing the configuration would always return false for the resources prior to the last 'SPManagedMetadataServiceApp'. 
Also adding these two new properties as key would be no help, as the Name of the Managed Metadata service is a key and the combination of these three settings would be still unique.

@wfeaser Is it right, that there can only be one default for each of these settings?

Starting with this knowledge I would prefer a new resource, that handles this setting. Otherwise there can be several 'SPManagedMetadataServiceApp' resources in the configuration and the last would be applied.

```
SPManagedMetadataServiceAppDefault Name {
     DefaultColumnProxyName = "Name of the Managed MetadataService Proxy"
     DefaultKeywordProxyName = "Name of the Managed MetadataService Proxy"
}
```

**Comment by ykuijs** [comment]
@andikrueger I now see that I misunderstood the question of @wfeaser. You are absolutely right that SPManagedMetadataServiceApp is not the best place to configure these settings. I agree that a new resource is the best way of solving this issue.

**Comment by andikrueger** [comment]
@ykuijs Should we delete the following lines in the SPManagedMetadataServiceApp resource:
```
272 -DefaultKeywordTaxonomy `
273 -DefaultSiteCollectionTaxonomy`
```
They are kind of obsolete if we create a new resource for this setting?

**Comment by ykuijs** [comment]
@andikrueger Absolutely!

**Comment by ykuijs** [comment]
@andikrueger Are you going to pick up this issue and add it to your PR? Or do I have to leave it as "Help Wanted"?

**Comment by andikrueger** [comment]
@ykuijs I will be very busy the next two to three weeks. If this is not too late, I'm fine with creating this new resource.

**Comment by ykuijs** [comment]
Sure, no problem

**Comment by andikrueger** [comment]
@ykuijs are you working on this issue? I could take over.

**Comment by ykuijs** [comment]
@andikrueger I thought you were already working on this :-) If you have the opportunity to finish this by the end of this week, we can include it in v2.0......no pressure :-p

**Comment by ykuijs** [comment]
Closed via PR 699
