### ISSUE TITLE
How do we use custom solution ?

### ISSUE THREAD

**Issue by Tpaquot** [PowerShell/SharePointDsc#733]
Windows 2012 r2 / Sharepoint 2013 SP1 / ShareointDSC 2.0.0.0
The DSC config went first OK 
I tried to import a custom solution from brightstore 
And It went OK too 
SPFarmSolution FreeBWorkPSTemplate #ResourceName
        {
            LiteralPath = "c:\wsp\Free BrightWork Project Structured Template for SharePoint.wsp"
            Name = "Free BrightWork Project Structured Template for SharePoint.wsp"
            DependsOn = '[SPSite]TeamSite'
            Deployed = $true
            Ensure = "Present"
            PsDscRunAsCredential = $SPSetupAccount
            SolutionLevel = "15"
            Version = "1.0.0.0"]

the result is ...
VERBOSE: [DSCSP]:                            [[SPFarmSolution]FreeBWorkPSTemplate] Result: DeploymentSucceeded
VERBOSE: [DSCSP]:                            [[SPFarmSolution]FreeBWorkPSTemplate] Details: DSCSP : The solution was successfully depl
oyed.
... 

Although it seems OK, when I checked on the custom template, I can see anything

Any help would be welcome 
Regards 
Thierry

**Comment by ykuijs** [comment]
Hi @Tpaquot, what do you see in Solution Deployment in Central Admin? Is the solution deployed successfully?

**Comment by Tpaquot** [comment]
Yes, I do see them in system settings / manage farm solution. 
They are globally deployed. 
I see them, when I run Get-SPSolution
They do not appear when I do a Get-SPWebTemplate
How do I carry on and use this solution in a site ?

**Comment by NikCharlebois** [comment]
I recommend you follow up with the solution provider. Most custom solutions require you to enable a feature at the Farm, WebApplication, SPSite or SPWeb level for the bits to be made available.

**Comment by ykuijs** [comment]
Hi @Tpaquot, I just checked the [Install Guide](https://www.brightwork.com/resources/free-sharepoint-project-management-templates/free-templates-install-guide) of the solution and the solution is not a farm solution, but a Sandboxed solution. According to the guide, you have to upload the solution to a site collection solution gallery, after which the template will become available for that site collection.

In that case, it does not work to install the solution as a farm solution unfortunately.

Closing this issue, since this is not SharePointDsc related.
