### ISSUE TITLE
Access Denied Problem with SPAppCatalog : proposal solution

### ISSUE THREAD

**Issue by paololec** [PowerShell/SharePointDsc#872]
### Description
To solve the access denied problem with SPAppCatalog and setup account need execute code with high privileges. Using farm account not always resolve problem if need remote connection and farm account is not local admin.

### Proposed properties
fix code with high privileges:
[Microsoft.SharePoint.SPSecurity]::RunWithElevatedPrivileges({ 
            Update-SPAppCatalogConfiguration -Site $params.SiteUrl -Confirm:$false 
            })

**Comment by ykuijs** [comment]
Since v2.5 the resource requires the InstallAccount or PsDscRunAsCredential **NOT** to be the farm account. It then retrieves the farm account, temporarily adds it to the local administrators group, runs Update-SPAppCatalogConfiguration and then removes the account from the local administrators group again. This should solve the issue you are describing.

Can you please test using v2.5 if the issue you are running into is resolved?

**Comment by ykuijs** [comment]
@paololec Were you able to test v2.5 yet?

**Comment by paololec** [comment]
None, but I resolved with custom script :
$webApp.GrantAccessToProcessIdentity("$env:USERDOMAIN\$env:USERNAME")
because I found that the setup account missing permission for appcatalog configuration and other things related to sites.

**Comment by ykuijs** [comment]
Ok, in that case closing issue since issue should be resolved with v2.5
