### ISSUE TITLE
SPSitePropertyBag: Add resource to set site collection property bag

### ISSUE THREAD

**Issue by jensotto** [PowerShell/SharePointDsc#885]
### Description
Add a resource for modifying site collection property bag. This could be similar to the existing SPFarmProeprtyBag
### Proposed properties
SiteCollectionUrl: The URL of the site collection
Key: The key of the SPSite property bag
Value: Value of the SPSite property bag
Ensure: Set to present to ensure the SPSite property exists, or absent to ensure it is removed

### Special considerations or limitations
I'm debating if this resource is really needed as it's easy to just use CSOM and SharePoint PnP PowerShell. It might however be useful in some cases.

**Comment by ykuijs** [comment]
This is indeed a debatable resource. Up until now we have limited ourself to resources that do not go deeper than site collection level (SPWeb is an exception because that was fully developed and submitted as a PR. Was a waste of time not to include it ;-)). Mainly because this can cause conflict with actions of site owners, for example:
A configuration contains a SPWeb resource to create a subsite. The site collection owner deletes that site. SharePointDsc detects that and recreates the site again. That can cause confusion with the site collections owners/admins.

In this case, the site collection property bag cannot be set via the UI, which makes it less likely that site collection owners will update these settings themselves. However, like you say it is possible to set these via CSOM or PnP PowerShell.

@NikCharlebois What is you opinion on this resource suggestion?

**Comment by ykuijs** [comment]
@NikCharlebois Am interested in your opinion on this resource suggestion.

**Comment by NikCharlebois** [comment]
I am also on the fence for whether or not it makes sense to include it. I have always been against using DSC for data (basically anything that you don't need Central Admin to create). However, from a ReverseDSC perspective where you wish to recreate an empty copy of an existing farm, but do not plan on bring the content databases over, it makes a lot of sense. Because of this scenario, I'd say it would be a great addition to the module. I know tons of 3rd party that won't function properly without this, and it has been an issue for some DSC engagement in the past.

**Comment by ykuijs** [comment]
There is no UI for configuring these settings anywhere, not in Central Admin nor in a Site Collection. That is why I am in favor of adding this resource.

Let's go for it! Marking it as "Help Wanted"

**Comment by shurick81** [comment]
Hi, two questions:
1. Does SPSite in SharePoint even have property bag?
2. Is this change documented in SharePointDsc Wiki?

**Comment by ykuijs** [comment]
Good point, the SPSite object doesn't have a property bag, but the RootWeb has. Although technically this would make it a SPWeb property bag :-p

Not sure how this slipped my testing. Will update the resource!

**Comment by ykuijs** [comment]
The Wiki doc can be found [here](https://github.com/PowerShell/SharePointDsc/wiki/SPSitePropertyBag)
